name: product
version: 1.0.0+1
publish_to: none
description: product project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  sqflite: 2.2.8+4
  image_picker: ^1.0.2
  path_provider:
  path:
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/image/



